### ISSUE TITLE
Disconnected MongoScope Connection Problem

### ISSUE THREAD

**Issue by jjflyboy** [nlloyd/horn-of-mongo#12]
Hi, I'm trying to connect to a local mongo instance using the Disconnected MongoScope method and the call to MongoRuntime.call() is throwing a syntax error exception when I use a password with special characters, e.g., "?" and "~".  If I start mongod without using the "--auth" option and remove user/pass from the connection string in the call to new MongoScriptAction(), everything works as expected.  The error appears to be in the call to the cx.evaluateString method inside MongoScriptAction.doRun method.

Any help is appreciated, thanks.

**Comment by jjflyboy** [comment]
Breaking the authentication into a separate call appears to have solved the issue: 
   MongoRuntime.call(new MongoScriptAction(myMongoScope, "auth", "auth = db.auth('someuser','somepwd');"));

**Comment by nlloyd** [comment]
I have seen this issue before.  It lies in how Rhino parses script strings and I have not been able to patch around it.  Since there is a workaround right now I am not in any hurry to fix this.
